### ISSUE TITLE
Current mode of operation has consequences

### ISSUE THREAD

**Issue by MPeti1** [accwebs/factorio-tacticalConstruction#5]
First, if you turn on "toggle prioritize local construction" then you won't be able to use the planners and planner like tools on entities you previously built until you turn it back off.
Second, if you leave it turned on, start researching, and then realize you need to it switch back because of the above reason, you will lose any research progress you made since activating the toggle.

I think it's not a good idea to mess with forces, because the game itself wants to use it in other ways. Like it won't sync research and permissions, and probably there are other consequences too.

I've noticed though that the entities that are built in the local prioritized mode get reassigned to the player force when I turn it off. Not sure how you do that (I don't know much about Factorio modding), but if you could make that work for research too, then it could be ok.

Still, managing every such thing "by hand" instead of leaving it to the game will create problems when the game gets new force dependent features officially or by mods, so I would recommend to avoid this way, or make a big warning about the consequences, that it may have bad effects that may only be noticed long into the game.

**Comment by accwebs** [comment]
Hi MPeti1,

> First, if you turn on "toggle prioritize local construction" then you won't be able to use the planners and planner like tools on entities you previously built until you turn it back off.
Second, if you leave it turned on, start researching, and then realize you need to it switch back because of the above reason, you will lose any research progress you made since activating the toggle.

Indeed.  There are a number of downsides to creating the alternative force and switching the player around as the Readme (and detailed mod description) states.  See:
 * https://github.com/accwebs/factorio-tacticalConstruction#considerations
 * https://github.com/accwebs/factorio-tacticalConstruction#limitations

In particular - yes - I would 100% avoid trying to do any research while you're on the alternative force since any progress there will likely be lost :-/ given the two separate forces.  Maybe the action item for this issue is to add that to the considerations/limitations section?

Keep in mind, the toggle was never intended to be left on for very long.  (Usually I only key it on briefly when I notice my robots aren't doing what I want them to do.)

> I think it's not a good idea to mess with forces, because the game itself wants to use it in other ways. Like it won't sync research and permissions, and probably there are other consequences too.

Unfortunately, I didn't see any avenue for accomplishing what this mod does outside of using multiple forces in the game.  If you think you've found a better way to do it, by all means raise a PR.  

> I've noticed though that the entities that are built in the local prioritized mode get reassigned to the player force when I turn it off. Not sure how you do that (I don't know much about Factorio modding), but if you could make that work for research too, then it could be ok.

Interesting suggestion.  I definitely *could* add logic to transfer any completed research on the alternative force back to the primary force (since I'm already syncing primary -> alternate), but I almost wonder if that's such a hot idea.  I don't want to really encourage people to research things while the toggle is on, because AFAIK there is no way to transfer the state of in-progress research...

Thoughts?

> or make a big warning about the consequences, that it may have bad effects that may only be noticed long into the game.

I thought I *had* done this given the detailed mod description and warnings at the top.  Still, maybe these are not worded the way they need to be.  PRs are welcome if you have better wording in mind :-)

**Comment by MPeti1** [comment]
Sorry for the late answer. I was lost in a lot of notifications, and no I started catching up with Github notifications.

> Interesting suggestion. I definitely could add logic to transfer any completed research on the alternative force back to the primary force (since I'm already syncing primary -> alternate), but I almost wonder if that's such a hot idea. I don't want to really encourage people to research things while the toggle is on, because AFAIK there is no way to transfer the state of in-progress research...
> 
> Thoughts?

Because of the limitations, maybe it's best if people are not researching while prioritization is on.
I think it should be more highlighted how this mod is intended to be used (as you said, not constantly on, but only when really needed) maybe even in-game? Also, there could be chat messages when a research is started in prioritization mode to warn the player to stop the research or progress will be lost, or if the game lets you, you could disable research in the custom made force

How are entities built in prioritization mode transferred to the regular force when turning the mode off?

**Comment by accwebs** [comment]
I (finally) added logic that prevents a player from accidentally starting research while on the 'alternative' force in the game.  It also sends a chat message explaining why the research was not allowed to be started. 

This will be part of version 0.4.0 (not released yet).

**Comment by accwebs** [comment]
I also have logic (as of 0.3.0) that can revert the force changes that the mod has made to a saved file.  You can use that to revert the state changes the mod has made to a file.

**Comment by accwebs** [comment]
> 
> How are entities built in prioritization mode transferred to the regular force when turning the mode off?

Yeah so the way this works is that I revert any 'alternative force' entities back to the primary force of the player as soon as the entities are out of range of all currently-prioritized player's local roboports.  

So, in other words, if you turn off the toggle, and nobody else A) has the toggle on and B) is in range of the now-constructed entity, it gets sent back to the primary force

**Comment by accwebs** [comment]
I think I've resolved the concrete action items that came out of the discussion on this issue.  If not, feel free to re-open.
